package dev.overequal.text

/**
 * Curated slur / profanity wordlists, ported from the reference `wordlists.py`.
 *
 * The reference distinguishes **slurs** (words that demean a protected group)
 * from **profanity** (vulgar swearing). Matching here is whole-token (the lists
 * already enumerate the inflected forms that occur), case-insensitive — a simpler
 * approximation of the reference's leetspeak-aware matcher.
 */
object Profanity {
    enum class Kind { SLUR, PROFANITY }

    val SLURS: Set<String> =
        hashSetOf(
            "faggot",
            "faggots",
            "fag",
            "fags",
            "fagg",
            "fagot",
            "fagging",
            "gaylord",
            "dyke",
            "dykes",
            "lesbo",
            "lesbos",
            "lezzy",
            "lez",
            "retard",
            "retards",
            "retarded",
            "tard",
            "fucktard",
            "spaz",
            "schizo",
            "nigga",
            "nig",
            "niglet",
            "negro",
            "coon",
            "kike",
            "kikes",
            "paki",
            "gook",
            "wigger",
            "wog",
            "chink",
            "spic",
            "whitey",
        )

    val PROFANITY: Set<String> =
        hashSetOf(
            "fuck",
            "fuk",
            "fck",
            "fcuk",
            "fack",
            "fook",
            "feck",
            "fucks",
            "fucked",
            "fucking",
            "fuckin",
            "fucker",
            "fuckers",
            "fuckass",
            "fuckhead",
            "fuckheads",
            "fuckface",
            "fuckup",
            "fuckhole",
            "fucktards",
            "motherfuck",
            "motherfucker",
            "motherfuckers",
            "motherfucking",
            "mothafucka",
            "mothafucker",
            "mofo",
            "shitfuck",
            "assfuck",
            "shit",
            "shite",
            "shits",
            "shitt",
            "shitty",
            "shitting",
            "shitter",
            "shitters",
            "shithole",
            "shithead",
            "bullshit",
            "shitted",
            "ass",
            "asses",
            "asshole",
            "assholes",
            "dumbass",
            "dumbasses",
            "fatass",
            "jackass",
            "arse",
            "wazoo",
            "bitch",
            "bitches",
            "bitching",
            "bitchin",
            "cunt",
            "cunts",
            "dick",
            "dickhead",
            "dicks",
            "cock",
            "cocks",
            "cocksucker",
            "cocksucking",
            "pussy",
            "pussies",
            "prick",
            "pricks",
            "twat",
            "twats",
            "knob",
            "knobhead",
            "knobend",
            "bellend",
            "bollocks",
            "bastard",
            "slut",
            "sluts",
            "whore",
            "whores",
            "wanker",
            "wank",
            "douchebag",
            "douche",
            "scumbag",
            "piss",
            "pissed",
            "pissing",
            "pisses",
            "pisser",
            "pissin",
            "damn",
            "goddamn",
            "goddammit",
            "goddam",
            "goddamnit",
            "crap",
            "bastards",
        )

    /** Classify a lowercased token, or null if it is neither. Slurs take precedence. */
    fun categorize(token: String): Pair<Kind, String>? =
        when {
            token in SLURS -> Kind.SLUR to token
            token in PROFANITY -> Kind.PROFANITY to token
            else -> null
        }
}
